import type { CreateRelationshipInput } from '@/application/actions/action-types.ts';
import type { JoinKind, RelationshipKeyPair, RelationshipKind } from '@/domain/relationship/relationship.ts';
import type { DataCanvasTool, ToolDependencies } from '@/webmcp/registry/tool-types.ts';
import { toolSchemas } from '@/webmcp/schemas/compile-schemas.ts';
import { asInput, failure, success } from '@/webmcp/tools/tool-helpers.ts';

// Creates a relationship from validated dataset and column IDs.
export const createCreateRelationshipTool = (deps: ToolDependencies): DataCanvasTool => ({
  name: 'create_relationship',
  description:
    'Relate two datasets on key columns so analysis can span them. Join SQL is generated by the application; only dataset and column IDs are accepted.',
  schema: toolSchemas.create_relationship,
  annotations: { readOnlyHint: false },
  needsDataset: true,
  handler: async (raw) => {
    const input = asInput(raw);
    const payload: CreateRelationshipInput = {
      leftDatasetId: input.leftDatasetId as string,
      rightDatasetId: input.rightDatasetId as string,
      on: input.on as RelationshipKeyPair[],
      kind: input.kind as RelationshipKind,
      join: input.join as JoinKind,
    };

    const result = await deps.dispatcher.execute(
      { type: 'relationship.create', payload },
      { actor: 'agent', expectedRevision: input.expectedRevision as number },
    );

    if (!result.ok) return failure(result.error);

    return success({
      revision: result.value.revision,
      // Return the fan-out warning from the action summary.
      summary: result.value.summary,
      relationshipId: result.value.changedEntityIds[0],
    });
  },
});
