import type { Column } from '@/domain/dataset/dataset.ts';
import type { DomainError } from '@/shared/errors/domain-error.ts';
import type { EntityId } from '@/shared/ids/entity-id.ts';
import { err } from '@/shared/result/result.ts';
import type { Result } from '@/shared/result/result.ts';

/**
 * What the analytical engine returns after ingesting a file into an internal relation.
 *
 * `relationId` is generated by the engine and never derived from the uploaded filename, so a file
 * named `Q4 sales; DROP TABLE x.csv` still maps to an opaque internal identifier.
 */
export interface ImportedRelation {
  relationId: string;
  rowCount: number;
  columns: Column[];
}

/**
 * The application's view of the analytical engine.
 *
 * Declared here, in the application layer, so handlers depend on a port rather than on
 * DuckDB-Wasm. The concrete engine is supplied later and plugs in without any handler change.
 *
 * Only the operations the current action handlers need appear here. Query execution and windowed
 * reads are added by the plans that introduce their callers, keeping the port free of speculative
 * surface.
 */
export interface DataEnginePort {
  importFile(file: unknown, datasetId: EntityId): Promise<Result<ImportedRelation, DomainError>>;
}

/**
 * The placeholder engine used until a real one exists.
 *
 * It fails rather than pretending to succeed: an action that silently no-ops would commit a
 * `Dataset` describing a relation that was never created, and every later query against it would
 * fail with a far less obvious error.
 */
export const unavailableDataEngine: DataEnginePort = {
  importFile: () =>
    Promise.resolve(err({ code: 'ENGINE_UNAVAILABLE', message: 'The analytical engine is not available yet.' })),
};
