import type { Column } from '@/domain/dataset/dataset.ts';
import type { AnalysisQuery, SortSpec } from '@/domain/analysis/analysis-query.ts';
import type { ColumnRange } from '@/domain/analysis/bin-strategy.ts';
import type { Filter } from '@/domain/filter/filter.ts';
import type { ResultColumn } from '@/data/compiler/result-columns.ts';
import type { DomainError } from '@/shared/errors/domain-error.ts';
import type { EntityId } from '@/shared/ids/entity-id.ts';
import { err } from '@/shared/result/result.ts';
import type { Result } from '@/shared/result/result.ts';

/**
 * What the analytical engine returns after ingesting a file into an internal relation.
 *
 * `relationId` is generated by the engine and never derived from the uploaded filename, so a file
 * named `Q4 sales; DROP TABLE x.csv` still maps to an opaque internal identifier.
 */
export interface ImportedRelation {
  relationId: string;
  rowCount: number;
  columns: Column[];
}

/**
 * A bounded read of consecutive rows.
 *
 * `limit` is a request, not a guarantee: the engine caps it. Rows are positional arrays rather than
 * keyed objects because column identity already lives in the domain `Column[]`, and rebuilding a
 * key per cell would allocate a property name per value for every row read.
 */
export interface TableWindowRequest {
  datasetId: EntityId;
  offset: number;
  limit: number;
  sort?: SortSpec[];
  filters: Filter[];
  signal?: AbortSignal;
}

export interface TableWindow {
  rows: readonly (string | number | boolean | null)[][];
  /** Column IDs in result order, so a caller maps cells to domain columns without guessing. */
  columnIds: readonly EntityId[];
  offset: number;
  /**
   * True when a newer request for the same logical work superseded this one. The caller discards
   * the window rather than rendering it, which is what prevents an older, slower read from
   * overwriting a newer one.
   */
  stale: boolean;
  columns: ResultColumn[];
  totalRowCount: number;
}

export interface AnalysisResult {
  rows: readonly (string | number | boolean | null)[][];
  columns: ResultColumn[];
  /**
   * Advisory text about the result's trustworthiness, currently join fan-out.
   *
   * Value-free by contract, since it is shown in the UI and returned to agents. Present only when
   * there is something to say, so callers can treat its absence as "nothing detected".
   */
  warning?: string;
}

export interface DistinctValuesRequest {
  datasetId: EntityId;
  columnId: EntityId;
  filters: Filter[];
  limit?: number;
  signal?: AbortSignal;
}

export interface DistinctValue {
  value: string | number | boolean | null;
  count: number;
}

export interface DistinctValuesResult {
  values: DistinctValue[];
  truncated: boolean;
}

/**
 * A single-pass profile of one column.
 *
 * Every field is an aggregate, so the result size is fixed regardless of dataset size. `topValues`
 * is the exception and carries actual cell content, which is why it is capped and why the tool
 * exposing it is marked as returning untrusted content.
 */
export interface ColumnStatisticsRequest {
  datasetId: EntityId;
  columnId: EntityId;
  filters: Filter[];
  /** Cap on returned frequent values. The engine clamps it. */
  topValueLimit?: number;
  signal?: AbortSignal;
}

export interface ColumnStatistics {
  rowCount: number;
  nullCount: number;
  /** Capped: equal to the cap means "at least this many", not an exact count. */
  distinctCount: number;
  distinctCountCapped: boolean;
  /** Present for numeric columns only. */
  min?: number;
  max?: number;
  mean?: number;
  median?: number;
  stddev?: number;
  /** Present for text and category columns only. Values are dataset content. */
  topValues?: { value: string | number | boolean | null; count: number }[];
}

/**
 * The numeric extent of a column, needed before an equal-width bin strategy can be compiled.
 *
 * Cached against the dataset revision by the caller. Recomputing it on every histogram render would
 * add a full scan to each frame.
 */
export interface ColumnRangeRequest {
  datasetId: EntityId;
  columnId: EntityId;
  filters: Filter[];
  signal?: AbortSignal;
}

/**
 * A bounded uniqueness measurement over a candidate join key.
 *
 * Sampled rather than exhaustive so relationship creation stays interactive on a large dataset. The
 * result is evidence for a warning, never grounds for rejecting a join.
 */
export interface KeyQualityRequest {
  datasetId: EntityId;
  columnIds: EntityId[];
  sampleRows: number;
  signal?: AbortSignal;
}

export interface KeyQualityResult {
  sampledRows: number;
  distinctKeys: number;
}

/**
 * The application's view of the analytical engine.
 *
 * Declared here, in the application layer, so handlers depend on a port rather than on DuckDB-Wasm.
 * No DuckDB type appears in this file and no connection object crosses it.
 *
 * Only the operations the current callers need appear here. Analysis-query execution and distinct
 * value reads arrive with the plan that introduces their callers, keeping the port free of
 * speculative surface.
 */
export interface DataEnginePort {
  importFile(file: unknown, datasetId: EntityId): Promise<Result<ImportedRelation, DomainError>>;
  fetchTableWindow(request: TableWindowRequest): Promise<Result<TableWindow, DomainError>>;
  executeAnalysis(query: AnalysisQuery): Promise<Result<AnalysisResult, DomainError>>;
  getDistinctValues(request: DistinctValuesRequest): Promise<Result<DistinctValuesResult, DomainError>>;
  getColumnStatistics(request: ColumnStatisticsRequest): Promise<Result<ColumnStatistics, DomainError>>;
  getColumnRange(request: ColumnRangeRequest): Promise<Result<ColumnRange, DomainError>>;
  measureKeyQuality(request: KeyQualityRequest): Promise<Result<KeyQualityResult, DomainError>>;
  /** Drops a dataset's relation and its cached counts. Idempotent: an unknown dataset succeeds. */
  dropDataset(datasetId: EntityId): Promise<Result<void, DomainError>>;
}

/**
 * The placeholder engine used before initialization completes, and in tests that exercise handler
 * logic without an engine.
 *
 * It fails rather than pretending to succeed: an action that silently no-ops would commit a
 * `Dataset` describing a relation that was never created, and every later query against it would
 * fail with a far less obvious error.
 */
const unavailable = (): Result<never, DomainError> =>
  err({ code: 'ENGINE_UNAVAILABLE', message: 'The analytical engine is not available yet.' });

export const unavailableDataEngine: DataEnginePort = {
  importFile: () => Promise.resolve(unavailable()),
  fetchTableWindow: () => Promise.resolve(unavailable()),
  executeAnalysis: () => Promise.resolve(unavailable()),
  getDistinctValues: () => Promise.resolve(unavailable()),
  getColumnStatistics: () => Promise.resolve(unavailable()),
  getColumnRange: () => Promise.resolve(unavailable()),
  measureKeyQuality: () => Promise.resolve(unavailable()),
  dropDataset: () => Promise.resolve(unavailable()),
};
