/**
 * The single source of SQL identifiers.
 *
 * Security invariant. No identifier anywhere in the application may be built by interpolating a
 * filename, a column header, or agent input into SQL text. A file called
 * `Q4 sales; DROP TABLE x.csv` maps to a generated `dataset_<hex>` relation; its original name is
 * display text and never reaches the database as an identifier.
 *
 * Value safety is a separate mechanism: parameters cannot bind identifiers, so quoting and
 * parameter binding operate together rather than as alternatives.
 */

/**
 * The shape every identifier must already have before it can be quoted.
 *
 * Deliberately narrow: lowercase ASCII, digits, and underscore, starting with a letter, at most 63
 * characters — DuckDB's identifier limit. Anything richer would widen the surface this module
 * exists to keep closed.
 */
export const SAFE_IDENTIFIER_PATTERN = /^[a-z][a-z0-9_]{0,62}$/;

/** Prefix that marks a relation as application-generated rather than user-derived. */
const RELATION_PREFIX = 'dataset_';

/** Hex characters taken from the entity ID. 12 keeps collisions negligible and names readable. */
const RELATION_HEX_LENGTH = 12;

export const isSafeIdentifier = (name: string): boolean => SAFE_IDENTIFIER_PATTERN.test(name);

/**
 * Derives the internal relation name for a dataset.
 *
 * Derived from the entity ID — itself generated by `createEntityId`, never from user input — so the
 * mapping is stable across a session: re-deriving it yields the same relation rather than orphaning
 * the one already created.
 *
 * The `ds_` prefix is dropped first. Its `d` is itself a hex character, so keeping it would shift
 * every relation name by one and make the identifier depend on the prefix's spelling rather than
 * on the UUID alone. Remaining non-hex characters are then stripped, and the result padded, so the
 * allowlist holds even if the ID format later changes.
 */
export const createRelationName = (datasetId: string): string => {
  const withoutPrefix = datasetId.slice(datasetId.indexOf('_') + 1);
  const hex = withoutPrefix.replace(/[^0-9a-f]/gi, '').toLowerCase();
  const padded = (hex + '0'.repeat(RELATION_HEX_LENGTH)).slice(0, RELATION_HEX_LENGTH);

  return `${RELATION_PREFIX}${padded}`;
};

/**
 * Quotes an identifier for inclusion in SQL.
 *
 * Throws rather than sanitizes. A non-conforming identifier means trusted application code
 * constructed one incorrectly — a programming error. Silently repairing it would let that bug ship
 * and would turn this module from a guarantee into a best effort.
 *
 * The embedded-quote doubling is defence in depth: the allowlist already rejects `"`, so the escape
 * can never fire, but it keeps the function correct if the pattern is ever widened.
 */
export const quoteIdentifier = (name: string): string => {
  if (!isSafeIdentifier(name)) {
    // The rejected identifier is not interpolated: it can originate from imported file content,
    // and error text must stay free of dataset-derived values.
    throw new Error('Refusing to quote an identifier that does not match the safe-identifier allowlist.');
  }

  return `"${name.replaceAll('"', '""')}"`;
};

/** Suffix appended to a relation name for the transient relation ingestion writes into first. */
export const stagingRelationName = (relationName: string): string => `${relationName}_staging`;

/**
 * The virtual filesystem path a file is registered under during ingestion.
 *
 * Derived from the generated relation name rather than from the uploaded filename. DuckDB's file
 * readers take the path as a *string literal* in SQL, so a filename-derived path would be a second
 * injection surface alongside identifiers — and one that quoting an identifier would not cover.
 */
export const virtualImportPath = (stagingName: string): string => {
  if (!isSafeIdentifier(stagingName)) {
    throw new Error('Refusing to build an import path from a name outside the safe-identifier allowlist.');
  }

  return `${stagingName}.import`;
};

/**
 * The virtual filesystem path a Parquet export is written to and read back from.
 *
 * Derived from the generated relation name for the same reason `virtualImportPath` is: `COPY … TO`
 * and `read_parquet` both take the path as a SQL string literal, so a name originating outside this
 * module would be an injection surface that identifier quoting does not cover.
 */
export const virtualExportPath = (relationName: string): string => {
  if (!isSafeIdentifier(relationName)) {
    throw new Error('Refusing to build an export path from a name outside the safe-identifier allowlist.');
  }

  return `${relationName}.parquet`;
};

/**
 * Generates the physical column name at a given ordinal.
 *
 * DuckDB derives column names from the file's header row, so they are untrusted text: a header of
 * `"; DROP TABLE x` would become a column name no allowlist could accept, and a header containing
 * only unicode would produce nothing quotable at all. Instead of trying to sanitize headers, the
 * import renames every column positionally and keeps the original as display text.
 *
 * This is also what makes duplicate headers harmless — two columns named `region` land at distinct
 * ordinals and so receive distinct physical names.
 */
export const createColumnName = (ordinal: number): string => `c${ordinal}`;
